### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by pelegshilo** [tokern/piicatcher#134]
I installed piicatcher using pip and I get the above error whenever I try to run piicatcher, even just with --help. Here's the full traceback:
Traceback (most recent call last):
  File "C:\Users\Peleg.Shilo\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Peleg.Shilo\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Peleg.Shilo\PycharmProjects\EMRIdeTest\venv\Scripts\piicatcher.exe\__main__.py", line 4, in <module>
  File "c:\users\peleg.shilo\pycharmprojects\emridetest\venv\lib\site-packages\piicatcher\__init__.py", line 4, in <module>
    from piicatcher.api import scan_database, scan_file_object
  File "c:\users\peleg.shilo\pycharmprojects\emridetest\venv\lib\site-packages\piicatcher\api.py", line 12, in <module>
    from piicatcher.explorer.files import IO, Tokenizer
  File "c:\users\peleg.shilo\pycharmprojects\emridetest\venv\lib\site-packages\piicatcher\explorer\files.py", line 8, in <module>
    import magic
  File "c:\users\peleg.shilo\pycharmprojects\emridetest\venv\lib\site-packages\magic\__init__.py", line 208, in <module>
    libmagic = loader.load_lib()
  File "c:\users\peleg.shilo\pycharmprojects\emridetest\venv\lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by pelegshilo** [comment]
I managed to resolve this by running 
` pip uninstall python-magic
pip install python-magic-bin==0.4.14`
I will submit a PR to fix the pipfile

**Comment by vrajat** [comment]
Thanks for filling the issue and contributing a PR. I'll verify and accept.

**Comment by vrajat** [comment]
I've removed the feature to scan files.
