### ISSUE TITLE
psycopg2.errors.InvalidSchemaName: schema "<schemaname>" does not exist

### ISSUE THREAD

**Issue by yourssvk** [tokern/piicatcher#139]
Problem description:

For some schemas in Redshift, PII catcher returns this error:

Traceback (most recent call last):
  File "/Users/<username>/.env/bin/piicatcher", line 8, in <module>
    sys.exit(cli())
  File "/Users/<username>/.env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/<username>/.env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/<username>/.env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/<username>/.env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/<username>/.env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/<username>/.env/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/<username>/.env/lib/python3.9/site-packages/piicatcher/explorer/databases.py", line 113, in cli
    RelDbExplorer.dispatch(ns)
  File "/Users/<username>/.env/lib/python3.9/site-packages/piicatcher/explorer/explorer.py", line 59, in dispatch
    explorer.scan()
  File "/Users/<username>/.env/lib/python3.9/site-packages/piicatcher/explorer/explorer.py", line 96, in scan
    schema.scan(self._generate_rows)
  File "/Users/<username>/.env/lib/python3.9/site-packages/piicatcher/explorer/metadata.py", line 83, in scan
    child.scan(generator)
  File "/Users/<username>/.env/lib/python3.9/site-packages/piicatcher/explorer/metadata.py", line 126, in scan
    for row in generator(
  File "/Users/<username>/.env/lib/python3.9/site-packages/piicatcher/explorer/explorer.py", line 177, in _generate_rows
    query = self._get_query(schema_name, table_name, column_list)
  File "/Users/<username>/.env/lib/python3.9/site-packages/piicatcher/explorer/explorer.py", line 157, in _get_query
    count = self._get_table_count(schema_name, table_name)
  File "/Users/<username>/.env/lib/python3.9/site-packages/piicatcher/explorer/explorer.py", line 151, in _get_table_count
    cursor.execute(count)
psycopg2.errors.InvalidSchemaName: schema "<schemaname>" does not exist

Saw that this might be an issue with psycopg2 and redshift compatibility

Expected Result:

The Schema gets scanned

Actual Result:

The scanning fails...

**Comment by yourssvk** [comment]
user schema...

**Comment by yourssvk** [comment]
Wondering if this is the issue, let me check.. https://github.com/sqlalchemy/alembic/issues/610

**Comment by vrajat** [comment]
I am not sure if it is related. Can you run with `--debug`? That will provide more information on the internal flow. I am wondering if this has something to do with spaces or special characters in the name.

**Comment by yourssvk** [comment]
I did not face the issue when I retried today, with no changes...wondering if this is related to some timing issue (happens a few runs later or something?) - I can confirm that as i continue to test...

**Comment by yourssvk** [comment]
Ok Got the issue with that --log-level DEBUG option .. this option needs to be included to documentation

It was a table named like schemaname.schemaname.tablename (accidentally by some user most likely)

**Comment by yourssvk** [comment]
Table name was the problem...
