### ISSUE TITLE
Can't find model 'en_core_web_sm'

### ISSUE THREAD

**Issue by yourssvk** [tokern/piicatcher#150]
Traceback (most recent call last):
  File "/Users/username/tokern/.env/bin/piicatcher", line 8, in <module>
    sys.exit(app())
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/piicatcher/cli.py", line 251, in redshift
    op = scan_redshift(
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/piicatcher/api.py", line 308, in scan_redshift
    return scan_database(
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/piicatcher/api.py", line 121, in scan_database
    raise e
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/piicatcher/api.py", line 97, in scan_database
    deep_scan(
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/piicatcher/scanner.py", line 145, in deep_scan
    scanners = [RegexScanner(), NERScanner()]
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/piicatcher/scanner.py", line 68, in __init__
    self.nlp = spacy.load("en_core_web_sm")
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/Users/username/tokern/.env/lib/python3.9/site-packages/spacy/util.py", line 427, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

**Comment by vrajat** [comment]
Did you run `python -m spacy download en_core_web_sm` ?

Another option is to run with `--scan-type shallow`

**Comment by yourssvk** [comment]
python -m spacy download en

^^ solves the problem
