### ISSUE TITLE
Versions 0.16-0.17.1 fails to run when installed from pip

### ISSUE THREAD

**Issue by albert-salman** [tokern/piicatcher#151]
Hello,
Cannot start Athena scan 
with CLI command
 piicatcher scan  athena --name ExampleScan --region-name "us-east-1" --include-schema "names" --aws-access-key-id "key
" --aws-secret-access-key "secret" --s3-staging-dir "s3://aws-athena-query-results"

with error

/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/alembic/ddl/sqlite.py:74: UserWarning: Skipping unsupported ALTER for creation of implicit constraintPlease refer to the batch mode feature which allows for SQLite migrations using a copy-and-move strategy.
  util.warn(
Traceback (most recent call last):
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/bin/piicatcher", line 8, in <module>
    sys.exit(app())
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/piicatcher/cli.py", line 358, in athena
    op = scan_athena(
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/piicatcher/api.py", line 408, in scan_athena
    return scan_database(
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/piicatcher/api.py", line 121, in scan_database
    raise e
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/piicatcher/api.py", line 70, in scan_database
    scanner = DbScanner(
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/dbcat/catalog/db.py", line 61, in __init__
    self._extractor, self._conf = DbScanner._create_athena_extractor(source)
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/dbcat/catalog/db.py", line 303, in _create_athena_extractor
    conn_string_key: source.conn_string,
  File "/mnt/c/SalmanA/Projects/Privacy/Tokern/piic/lib/python3.8/site-packages/dbcat/catalog/models.py", line 143, in conn_string
    region_name=self.region,
AttributeError: 'CatSource' object has no attribute 'region'

**Comment by vrajat** [comment]
I've released v0.17.2 Can you please give that a try?

**Comment by albert-salman** [comment]
Working, thanks. I have now another issue - i can only use STS token based auth. For 0.15.0 i was able to correct code to add session token support because different pyathena connection method has been used, but for 0.16+ it is SQLAlchemy based rest access and sesson token seem to be not supported at all by AWS.
