### ISSUE TITLE
Unique Constraint Failed

### ISSUE THREAD

**Issue by vrajat** [tokern/piicatcher#199]
Hi @vrajat,

I get this error any idea? Thanks!

My attempt:

```
from dbcat.api import open_catalog, add_sqlite_source
from piicatcher.api import scan_database

catalog = open_catalog(app_dir='/tmp/.config/piicatcher', 
                        path='employee.db',
                        secret='my_secret')

with catalog.managed_session:
    # Add a postgresql source
    source = add_sqlite_source(catalog=catalog, 
                               name="employee",
                               path=r"employee.db")
    output = scan_database(catalog=catalog, source=source)

print(output)
```

The error
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute    
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: sources.name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/SEUMTE/Desktop/rack/work/privacy by design/piicatcher_demo/scan_sqlite.py", line 13, in <module>
    source = add_sqlite_source(catalog=catalog,
  File "C:\ProgramData\Anaconda3\lib\site-packages\dbcat\api.py", line 149, in add_sqlite_source
    catalog.add_source(name=name, uri=str(path), source_type="sqlite")
  File "C:\ProgramData\Anaconda3\lib\site-packages\dbcat\catalog\catalog.py", line 126, in add_source
    return self._create(CatSource, name=name, source_type=source_type, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dbcat\catalog\catalog.py", line 122, in _create
    session.flush()
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\session.py", line 2540, in flush
    self._flush(objects)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\session.py", line 2642, in _flush
    flush_context.execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: sources.name
[SQL: INSERT INTO sources (created_at, updated_at, source_type, name, uri, port, username, password, "database", cluster, project_id, project_credentials, page_size, filter_key, included_tables_regex, key_path, account, role, warehouse, aws_access_key_id, aws_secret_access_key, region_name, s3_staging_dir) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('sqlite', 'employee', 'C:\\Users\\SEUMTE\\Desktop\\rack\\work\\privacy by design\\piicatcher_demo\\employee.db', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

_Originally posted by @utekakca in https://github.com/tokern/piicatcher/issues/144#issuecomment-1300086320_

**Comment by vrajat** [comment]
The sqlite database already has a database named `employee`. Probably from a previous run. Can you use some other name? If you want to use the same name, then `add_sqlite_source` should be in an if condition where you check if it already exists. (There is an api to get all sources).
