### ISSUE TITLE
PII installation error 

### ISSUE THREAD

**Issue by suri1987** [tokern/piicatcher#235]
error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      Collecting setuptools>=40.6.0
        Obtaining dependency information for setuptools>=40.6.0 from https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl.metadata
        Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
        Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
      Collecting cython
        Obtaining dependency information for cython from https://files.pythonhosted.org/packages/ea/8f/216de5d7bede3e26a7131b427a8aadade032f03f9c8ee88792def02e2cf4/Cython-3.0.2-cp311-cp311-win_amd64.whl.metadata
        Using cached Cython-3.0.2-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
      Collecting pyarrow<8.1.0,>=8.0.0
        Using cached pyarrow-8.0.0.tar.gz (846 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
     
        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1
     
        [43 lines of output]
        <string>:36: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        Traceback (most recent call last):
          File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools\build_meta.py", line 396, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
            super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
            exec(code, locals())
          File "<string>", line 607, in <module>
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
            return distutils.core.setup(**attrs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
            _setup_distribution = dist = klass(attrs)
                                         ^^^^^^^^^^^^
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools\dist.py", line 303, in __init__
            _Distribution.__init__(self, dist_attrs)
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
            self.finalize_options()
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools\dist.py", line 680, in finalize_options
            ep(self)
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools\dist.py", line 700, in _finalize_setup_keywords
            ep.load()(self, ep.name, value)
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 102, in version_keyword
            _assign_version(dist, config)
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 54, in _assign_version
            maybe_version = _get_version(config, force_write_version_files=True)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools_scm\_get_version_impl.py", line 94, in _get_version
            write_version_files(config, version=version_string, scm_version=parsed_version)
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools_scm\_get_version_impl.py", line 63, in write_version_files
            dump_version(
          File "C:\Users\S\AppData\Local\Temp\pip-build-env-ge7vlulm\overlay\Lib\site-packages\setuptools_scm\_integration\dump_version.py", line 36, in dump_version
            assert not write_to.is_absolute(), f"{write_to=}"
        AssertionError: write_to=WindowsPath('C:/Users/S/AppData/Local/Temp/pip-install-y17nyst5/pyarrow_17895450960d42fcb0c069022d75975d/pyarrow/_generated_version.py')
        [end of output]
     
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
     
      Encountered error while generating package metadata.
     
      See above for output.
     
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by vrajat** [comment]
Can you paste the exact command you ran to install piicatcher?

**Comment by suri1987** [comment]
pip install PIIcatcher

**Comment by vrajat** [comment]
The only error message I see is 

```
 AssertionError: write_to=WindowsPath('C:/Users/S/AppData/Local/Temp/pip-install-y17nyst5/pyarrow_17895450960d42fcb0c069022d75975d/pyarrow/_generated_version.py')
```

This is a pyarrow installation issue on windows.
