### ISSUE TITLE
Deep Scan in Athena failing with HIVE_UNKNOWN_ERROR

### ISSUE THREAD

**Issue by vrajat** [tokern/piicatcher#63]
Yeah.. here its is...
[debug_log.txt](https://github.com/tokern/piicatcher/files/4196388/debug_log.txt)

_Originally posted by @jayeshagwan1 in https://github.com/tokern/piicatcher/issues/59#issuecomment-585534804_

**Comment by vrajat** [comment]
@jayeshagwan1 can you run `select count(*) from temp.pii_data` in Athena console ? 

Also the debug log seems to be truncated. Can you make sure that it contains all of the output ?

**Comment by jayeshagwan1** [comment]
I am having complete log, I have just scrapped and provided you a a certain portion. Will provide the complete log file in some time.

**Comment by vrajat** [comment]
I want to check these types of lines:

    DEBUG:root:Count Query: select count(*) from temp.pii_data 
    DEBUG:pyathena.common:select count(*) from temp.pii_data

**Comment by jayeshagwan1** [comment]
Not sure, but will this work ?
content-type;host;x-amz-date;x-amz-target
b06733bd35e2829482251739509d84a087c28becbebfe05d25c8cff2a696aa85
DEBUG:botocore.auth:StringToSign:
AWS4-HMAC-SHA256
20200212T134450Z
20200212/us-east-2/athena/aws4_request
998042b672348ed2bc07d1c5a54b96bf646cba76b98e6a6fdece665f9a84f99d
DEBUG:botocore.auth:Signature:
fc1e18a63921c402048de557688f0b464776dc41662d6d21f49ab60bd304253c
DEBUG:botocore.endpoint:Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://athena.us-east-2.amazonaws.com/, headers={'X-Amz-Target': b'AmazonAthena.GetQueryResults', 'Content-Type': b'application/x-amz-json-1.1', 'User-Agent': b'Boto3/1.10.34 Python/3.7.4 Windows/10 Botocore/1.13.50', 'X-Amz-Date': b'20200212T134450Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=*********************************/20200212/us-east-2/athena/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=fc1e18a63921c402048de557688f0b464776dc41662d6d21f49ab60bd304253c', 'Content-Length': '80'}>
DEBUG:urllib3.connectionpool:https://athena.us-east-2.amazonaws.com:443 "POST / HTTP/1.1" 200 4931
DEBUG:botocore.parsers:Response headers: {'Content-Type': 'application/x-amz-json-1.1', 'Date': 'Wed, 12 Feb 2020 13:44:49 GMT', 'x-amzn-RequestId': '65aebf7f-cda1-4beb-9958-a2313c64f1f5', 'Content-Length': '4931', 'Connection': 'keep-alive'}
DEBUG:botocore.parsers:Response body:
b'{"ResultSet":{"ColumnInfos":[{"CaseSensitive":true,"CatalogName":"hive","Label":"table_schema","Name":"table_schema","Nullable":"UNKNOWN","Precision":2147483647,"Scale":0,"SchemaName":"","TableName":"","Type":"varchar"},{"CaseSensitive":true,"CatalogName":"hive","Label":"table_name","Name":"table_name","Nullable":"UNKNOWN","Precision":2147483647,"Scale":0,"SchemaName":"","TableName":"","Type":"varchar"},{"CaseSensitive":true,"CatalogName":"hive","Label":"column_name","Name":"column_name","Nullable":"UNKNOWN","Precision":2147483647,"Scale":0,"SchemaName":"","TableName":"","Type":"varchar"}],"ResultRows":[{"Data":["table_schema","table_name","column_name"]},{"Data":["sampledb","elb_logs","request_timestamp"]},{"Data":["sampledb","elb_logs","elb_name"]},{"Data":["sampledb","elb_logs","request_ip"]},{"Data":["sampledb","elb_logs","backend_ip"]},{"Data":["sampledb","elb_logs","elb_response_code"]},{"Data":["sampledb","elb_logs","backend_response_code"]},{"Data":["sampledb","elb_logs","request_verb"]},{"Data":["sampledb","elb_logs","url"]},{"Data":["sampledb","elb_logs","protocol"]},{"Data":["sampledb","elb_logs","user_agent"]},{"Data":["sampledb","elb_logs","ssl_cipher"]},{"Data":["sampledb","elb_logs","ssl_protocol"]},{"Data":["temp","pii_data","phone"]},{"Data":["temp","pii_data","email"]},{"Data":["temp","pii_data","credit_card"]},{"Data":["temp","pii_data","address"]},{"Data":["temp","pii_data","person"]},{"Data":["temp","pii_data","location"]},{"Data":["temp","pii_data","gender"]},{"Data":["temp","pii_data","nationality"]},{"Data":["temp","pii_data","ip_address"]},{"Data":["temp","pii_data","ssn"]},{"Data":["testdb","test5","tst6"]},{"Data":["testdb","test6","tst7"]},{"Data":["testdb","test8","tst2"]},{"Data":["testdb","test9","tst11"]}],"ResultSetMetadata":{"ColumnInfo":[{"CaseSensitive":true,"CatalogName":"hive","Label":"table_schema","Name":"table_schema","Nullable":"UNKNOWN","Precision":2147483647,"Scale":0,"SchemaName":"","TableName":"","Type":"varchar"},{"CaseSensitive":true,"CatalogName":"hive","Label":"table_name","Name":"table_name","Nullable":"UNKNOWN","Precision":2147483647,"Scale":0,"SchemaName":"","TableName":"","Type":"varchar"},{"CaseSensitive":true,"CatalogName":"hive","Label":"column_name","Name":"column_name","Nullable":"UNKNOWN","Precision":2147483647,"Scale":0,"SchemaName":"","TableName":"","Type":"varchar"}]},"Rows":[{"Data":[{"VarCharValue":"table_schema"},{"VarCharValue":"table_name"},{"VarCharValue":"column_name"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"request_timestamp"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"elb_name"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"request_ip"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"backend_ip"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"elb_response_code"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"backend_response_code"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"request_verb"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"url"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"protocol"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"user_agent"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"ssl_cipher"}]},{"Data":[{"VarCharValue":"sampledb"},{"VarCharValue":"elb_logs"},{"VarCharValue":"ssl_protocol"}]},{"Data":[{"VarCharValue":"temp"},{"VarCharValue":"pii_data"},{"VarCharValue":"phone"}]},{"Data":[{"VarCharValue":"temp"},{"VarCharValue":"pii_data"},{"VarCharValue":"email"}]},{"Data":[{"VarCharValue":"temp"},{"VarCharValue":"pii_data"},{"VarCharValue":"credit_card"}]},{"Data":[{"VarCharValue":"temp"},{"VarCharValue":"pii_data"},{"VarCharValue":"address"}]},{"Data":[{"VarCharValue":"temp"},{"VarCharValue":"pii_data"},{"VarCharValue":"person"}]},{"Data":[{"VarCharValue":"temp"},{"VarCharValue":"pii_data"},{"VarCharValue":"location"}]},{"Data":[{"VarCharValue":"temp"},{"VarCharValue":"pii_data"},{"VarCharValue":"gender"}]},{"Data":[{"VarCharValue":"temp"},{"VarCharValue":"pii_data"},{"VarCharValue":"nationality"}]},{"Data":[{"VarCharValue":"temp"},{"VarCharValue":"pii_data"},{"VarCharValue":"ip_address"}]},{"Data":[{"VarCharValue":"temp"},{"VarCharValue":"pii_data"},{"VarCharValue":"ssn"}]},{"Data":[{"VarCharValue":"testdb"},{"VarCharValue":"test5"},{"VarCharValue":"tst6"}]},{"Data":[{"VarCharValue":"testdb"},{"VarCharValue":"test6"},{"VarCharValue":"tst7"}]},{"Data":[{"VarCharValue":"testdb"},{"VarCharValue":"test8"},{"VarCharValue":"tst2"}]},{"Data":[{"VarCharValue":"testdb"},{"VarCharValue":"test9"},{"VarCharValue":"tst11"}]}]},"UpdateCount":0}'
DEBUG:botocore.hooks:Event needs-retry.athena.GetQueryResults: calling handler <botocore.retryhandler.RetryHandler object at 0x00000212E5B93388>
DEBUG:botocore.retryhandler:No retry needed.
DEBUG:root:Count Query: select count(*) from temp.pii_data
DEBUG:pyathena.common:select count(*) from temp.pii_data
DEBUG:botocore.hooks:Event before-parameter-build.athena.StartQueryExecution: calling handler <function generate_idempotent_uuid at 0x00000212E55A0C18>
DEBUG:botocore.handlers:injecting idempotency token (e52c443e-831f-4dc0-8e3f-2b99ff0f71f2) into param 'ClientRequestToken'.
DEBUG:botocore.hooks:Event before-call.athena.StartQueryExecution: calling handler <function inject_api_version_header_if_needed at 0x00000212E55A3708>
DEBUG:botocore.endpoint:Making request for OperationModel(name=StartQueryExecution) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'X-Amz-Target': 'AmazonAthena.StartQueryExecution', 'Content-Type': 'application/x-amz-json-1.1', 'User-Agent': 'Boto3/1.10.34 Python/3.7.4 Windows/10 Botocore/1.13.50'}, 'body': b'{"QueryString": "select count(*) from temp.pii_data", "QueryExecutionContext": {"Database": "default"}, "ResultConfiguration": {"OutputLocation": "s3://pii-logs-test/piitest/2/1/"}, "ClientRequestToken": "e52c443e-831f-4dc0-8e3f-2b99ff0f71f2"}', 'url': 'https://athena.us-east-2.amazonaws.com/', 'context': {'client_region': 'us-east-2', 'client_config': <botocore.config.Config object at 0x00000212E5B79808>, 'has_streaming_input': False, 'auth_type': None}}
DEBUG:botocore.hooks:Event request-created.athena.StartQueryExecution: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x00000212E5B797C8>>
DEBUG:botocore.hooks:Event choose-signer.athena.StartQueryExecution: calling handler <function set_operation_specific_signer at 0x00000212E55A0168>
DEBUG:botocore.auth:Calculating signature using v4 auth.
DEBUG:botocore.auth:CanonicalRequest:

**Comment by vrajat** [comment]
I still see only `select count(*) from temp.pii_data` in the logs. I dont see any exceptions or errors. I want to know the last query that was run before the exception or error happened

**Comment by jayeshagwan1** [comment]
Sorry. Here is the log file if I dont hard code schema and table and just do select * 
[error_Log.txt](https://github.com/tokern/piicatcher/files/4196675/error_Log.txt)

**Comment by jayeshagwan1** [comment]
Even after passing schema and table from config, its still looking into all tables. It should fetch only mentioned schema and table.

**Comment by vrajat** [comment]
Can you test this query in athena console ? `select * from sampledb.elb_logs TABLESAMPLE BERNOULLI(5) limit 10` ? 

`sampledb.elb_logs` is created automatically and I think this is not setup properly or your account doesnt have access. 

can you try `piicatcher ... --exclude-schema sampledb`?

I'll look into "Even after passing schema and table from config, its still looking into all tables. It should fetch only mentioned schema and table." separately

**Comment by jayeshagwan1** [comment]
Traceback (most recent call last):                                                                                                                                                   File "F:\PII\pii_athena\piicatcher\.env\Scripts\piicatcher-script.py", line 11, in                                                                                           load_entry_point('piicatcher', 'console_scripts', 'piicatcher')()                                                                                                                File "F:\PII\pii_athena\piicatcher\.env\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__                                                                  return self.main(*args, **kwargs)                                                                                                                                                File "F:\PII\pii_athena\piicatcher\.env\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main                                                                      rv = self.invoke(ctx)                                                                                                                                                            File "F:\PII\pii_athena\piicatcher\.env\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke                                                                   return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                          File "F:\PII\pii_athena\piicatcher\.env\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke                                                                    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                   File "F:\PII\pii_athena\piicatcher\.env\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke                                                                    return callback(*args, **kwargs)                                                                                                                                                 File "F:\PII\pii_athena\piicatcher\.env\lib\site-packages\click-7.0-py3.7.egg\click\decorators.py", line 17, in new_func                                                             return f(get_current_context(), *args, **kwargs)                                                                                                                                 File "f:\pii\pii_athena\piicatcher\piicatcher\explorer\aws.py", line 57, in cli                                                                                                      AthenaExplorer.dispatch(args)                                                                                                                                                    File "f:\pii\pii_athena\piicatcher\piicatcher\explorer\explorer.py", line 58, in dispatch                                                                                            explorer.scan()                                                                                                                                                                  File "f:\pii\pii_athena\piicatcher\piicatcher\explorer\explorer.py", line 86, in scan                                                                                                schema.scan(self._generate_rows)                                                                                                                                                 File "f:\pii\pii_athena\piicatcher\piicatcher\explorer\metadata.py", line 53, in scan                                                                                                child.scan(generator)                                                                                                                                                            File "f:\pii\pii_athena\piicatcher\piicatcher\explorer\metadata.py", line 105, in scan                                                                                               col.scan(val, scanners)                                                                                                                                                          File "f:\pii\pii_athena\piicatcher\piicatcher\explorer\metadata.py", line 140, in scan                                                                                               [self._pii.add(pii) for pii in scanner.scan(data)]                                                                                                                               File "f:\pii\pii_athena\piicatcher\piicatcher\scanner.py", line 25, in scan                                                                                                          regex_result = CommonRegex(text)                                                                                                                                                 File "F:\PII\pii_athena\piicatcher\.env\lib\site-packages\commonregex-1.5.4-py3.7.egg\commonregex.py", line 53, in __init__                                                        File "F:\PII\pii_athena\piicatcher\.env\lib\site-packages\commonregex-1.5.4-py3.7.egg\commonregex.py", line 39, in regex_method                                                  TypeError: expected string or bytes-like object
--

**Comment by vrajat** [comment]
I just released a new version. Mostly with debug logging improvements. I do not know if it will fix all your issues. Please give it a try without any edits. Also please provide any debug logs for any issues.

On filtering tables, check my comment in #65 on the right syntax.

**Comment by jayeshagwan1** [comment]
In new version its working fine.
Some of columns are not getting identified as required PII data type.

**Comment by vrajat** [comment]
Can you provide examples in a new issue?

**Comment by jayeshagwan1** [comment]
Will this work ? Deep scan and shallow scan results are different.
[deepscan.txt](https://github.com/tokern/piicatcher/files/4198733/deepscan.txt)
[shallowscan.txt](https://github.com/tokern/piicatcher/files/4198736/shallowscan.txt)
